const WRITING_PROMPTS = [
    // Character
    "Write a scene that reveals your protagonist's greatest fear without naming it directly.",
    "What does your main character do when they think no one is watching? Write that moment.",
    "Write the scene where a secondary character surprises everyone — including you.",
    "Describe how your protagonist moves through a crowded room. What do they notice? What do they avoid?",
    "Write a conversation your character has been dreading for months. It's finally happening.",
    "What is something your protagonist believes is true that is actually wrong? Write the scene that hints at it.",
    "Write the backstory moment that explains why your character is the way they are today.",
    "Your character receives unexpected good news. How do they react?",
    "Describe what your character's home or living space looks like — and what that reveals about them.",
    "Write a moment when your character does something that surprises even themselves.",
    "Your protagonist is jealous of someone. Write the scene where that jealousy comes to a head.",
    "What does your character want more than anything? Write the moment they get closest to it.",
    "Write your character's morning routine in detail. What rituals do they have? What do they avoid?",
    "Your character runs into someone from their past. Write the encounter.",
    "What lie does your protagonist tell most often? Write the moment it almost catches up with them.",
    "Describe your protagonist's hands. What do they reveal about this person's life?",
    "Write a memory from your character's childhood that still shapes their decisions today.",
    "Your character is alone for an entire afternoon with nothing to do. What happens?",
    "Write the moment your protagonist decides to change — or tries to.",
    "Who does your character most want approval from? Write a scene with that person.",
    "Write a scene that shows your character's sense of humor — or lack of one.",
    "Your protagonist has a habit they're not proud of. Write a scene where it shows.",
    "What does your character look like when they're at ease? Write that moment of quiet.",
    "Write your protagonist doing something they're genuinely good at.",
    "Your character meets a stranger who reminds them uncomfortably of themselves.",

    // Scene and Setting
    "Describe a place in your story world as seen through the eyes of someone visiting it for the very first time.",
    "Write a scene set at an unusual time of day — 3am, at dawn, during the golden hour before sunset.",
    "A storm is coming. Write the scene that happens just before it arrives.",
    "Write a scene set in a place your protagonist loves but rarely visits.",
    "Describe the sounds and smells of a key location in your story. No visual description allowed.",
    "Write a scene set in an uncomfortable or dangerous environment. How does the setting change the characters?",
    "A place in your story wakes up. Describe the first hour of the morning there.",
    "Write a scene at a gathering — a party, a funeral, a market, a celebration. Who is there? What's the tension?",
    "Your protagonist is traveling somewhere. Write the journey, not just the arrival.",
    "Describe a threshold moment — a character standing at a literal or figurative doorway, deciding whether to cross.",
    "Write a scene in which the weather mirrors the emotional state of the moment.",
    "An old building, road, or place in your story has a history. Write a scene that hints at it.",
    "Write a night scene. What is different about the world at night in your story?",
    "Two characters are in a small, confined space together. What happens?",
    "Write the scene that first opens your story's world to the reader.",
    "Describe a place through the eyes of a character who hates being there.",
    "Write a scene where the setting itself feels like a character.",
    "Your protagonist returns to a place they haven't been in years. What's changed? What's the same?",
    "Write the most beautiful place in your story world. Why does it matter?",
    "Describe a place that feels safe — and the moment something threatens that safety.",

    // Plot and Conflict
    "Write the scene where everything your protagonist thought was true turns out to be wrong.",
    "Something goes wrong that no character planned for. Write the immediate aftermath.",
    "Write a scene where two characters want the same thing but for completely different reasons.",
    "A secret is about to be revealed. Write the scene leading up to the revelation.",
    "Your protagonist has to make an impossible choice. Write the moment of decision.",
    "Write the scene where the opposing force — a person, a system, a circumstance — gains the upper hand.",
    "Something small — an object, a letter, a name overheard — sets events in motion. Write that scene.",
    "Write a scene of conflict where both sides are right. There's no villain.",
    "Your protagonist fails at something important. Write the failure — not just what happened, but how it felt.",
    "Write the moment when your protagonist realizes they've been their own worst enemy.",
    "Something from the past arrives in the present — a person, an object, a consequence. Write the scene.",
    "Write the scene where your protagonist almost gives up.",
    "Two alliances are tested. Write the scene where at least one breaks.",
    "Write a scene of escalation — things are getting worse faster than anyone anticipated.",
    "Write the midpoint of your story: the moment when the goal shifts or deepens.",
    "Something is lost that cannot be recovered. Write the scene.",
    "Write a scene that plants a seed — something small now that will matter greatly later.",
    "An unexpected opportunity arrives. Write your protagonist's reaction and first move.",
    "Write a scene where a misunderstanding has serious consequences.",
    "The moment of reckoning: write the scene where your protagonist must answer for their choices.",
    "Write a scene where the stakes become real for the first time.",
    "Your protagonist discovers they were wrong about someone they trusted. Write the moment.",
    "Write a scene where a plan falls apart in an unexpected way.",
    "Something your protagonist tried to prevent happens anyway. Write what comes next.",
    "Write a scene where your protagonist has to ask for help.",

    // Dialogue
    "Write a conversation where one character is hiding something important.",
    "Two characters finally say what they've been meaning to say for months.",
    "Write an argument that's really about something else entirely.",
    "A character delivers news — good or bad — that changes everything.",
    "Write a conversation between two people who don't fully trust each other.",
    "Someone asks a question they already know the answer to. Write the scene.",
    "Write a conversation that ends in silence — the most important thing goes unsaid.",
    "Two characters negotiate. What does each one want? Who gets the better of it?",
    "Write a conversation full of subtext — the characters say one thing but mean another.",
    "Someone says goodbye. Write the scene.",
    "Two characters speak honestly with each other for the first time. Write what they say.",
    "A character reveals something about themselves they've never told anyone.",
    "Write a conversation that feels completely ordinary but carries enormous weight.",
    "Two characters meet for the first time. Write the exchange.",
    "A character asks for help. How do they ask, and how is it received?",
    "Write a scene where someone says exactly the wrong thing at exactly the wrong moment.",
    "Two characters finish each other's thoughts. Write a scene where they're completely in sync.",
    "Write a scene where words fail — a character can't say what they mean.",

    // Emotion and Inner Life
    "Write your protagonist's internal monologue during a moment of high stakes.",
    "Your character is grieving something. Write the scene three days after the loss — not the loss itself.",
    "Write a moment of pure, unguarded joy.",
    "Your protagonist is terrified but can't show it. Write the scene.",
    "Write the moment when your character finally allows themselves to hope.",
    "Guilt: your character did something they can't take back. Write how they carry it.",
    "Write a scene of profound exhaustion — physical, emotional, or both.",
    "Your protagonist is angry. Write the scene where they finally channel it into action.",
    "Write the moment of acceptance — a character letting go of something they've been holding onto.",
    "Loneliness: write a scene where your character feels completely alone, even surrounded by people.",
    "Write a scene of unexpected tenderness between two characters who don't usually show it.",
    "Your protagonist is ashamed. Write the moment they have to face it.",
    "Write a scene of quiet happiness — not dramatic, just deeply true.",
    "Your character misses someone. Write the moment when that missing becomes unbearable.",
    "Write the scene where your character finally feels safe.",
    "Write the last thought your protagonist has before falling asleep.",
    "Your character is pretending to be fine. Write what's actually happening inside.",
    "Write a scene where your protagonist is proud of something — even if they'd never say so.",

    // Momentum (for when you're stuck)
    "Write the scene that comes immediately after the last thing you wrote.",
    "Your protagonist wakes up. Write the next hour of their day.",
    "Pick any two characters in your story. Put them in a room and see what happens.",
    "Write the scene you've been avoiding.",
    "Write a scene that doesn't have to end up in the book — just to get to know your characters better.",
    "Skip forward one week in your story's timeline. What has changed?",
    "Write any scene that makes you feel something.",
    "Write a scene from the perspective of a character who is not your protagonist.",
    "What is the theme of your story? Write a scene that shows it without naming it.",
    "Write the ending you're working toward — or a single image, moment, or feeling from it.",
    "Write a scene that establishes what is truly at stake in your story.",
    "Introduce an object that will matter later. Plant it here, casually.",
    "Write the scene that gives a secondary character a life beyond their role in the plot.",
    "Write the scene your story has been building toward — even just as a rough draft to understand where you're headed.",
    "Write something — anything — just to break the silence on the page."
];

function getTodayPrompt() {
    const start = new Date(new Date().getFullYear(), 0, 0);
    const dayOfYear = Math.floor((new Date() - start) / 86400000);
    return WRITING_PROMPTS[dayOfYear % WRITING_PROMPTS.length];
}
